// <auto-generated />
using System;
using FestivalHue2020WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FestivalHue2020WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231124171451_FestivalHueV1.1")]
    partial class FestivalHueV11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.ChuongTrinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Arrange")
                        .HasColumnType("int");

                    b.Property<string>("ChuongTrinhContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuongTrinhName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LichDienId")
                        .HasColumnType("int");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("TypeInoff")
                        .HasColumnType("int");

                    b.Property<int>("TypeProgram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LichDienId");

                    b.ToTable("ChuongTrinh");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.ChuongTrinhDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChuongTrinhId")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("IdDoan")
                        .HasColumnType("int");

                    b.Property<int>("IdNhom")
                        .HasColumnType("int");

                    b.Property<string>("NhomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhId");

                    b.ToTable("chuongTrinhDetail");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.DiaDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.LichDien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LichDien");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.TinTuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.Ve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChuongTrinhId")
                        .HasColumnType("int");

                    b.Property<float>("Gia")
                        .HasColumnType("real");

                    b.Property<bool>("HopLe")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("QRCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhId");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.ChuongTrinh", b =>
                {
                    b.HasOne("FestivalHue2020WebAPI.Models.LichDien", null)
                        .WithMany("DetailList")
                        .HasForeignKey("LichDienId");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.ChuongTrinhDetail", b =>
                {
                    b.HasOne("FestivalHue2020WebAPI.Models.ChuongTrinh", null)
                        .WithMany("DetailList")
                        .HasForeignKey("ChuongTrinhId");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.Ve", b =>
                {
                    b.HasOne("FestivalHue2020WebAPI.Models.ChuongTrinh", "ChuongTrinh")
                        .WithMany()
                        .HasForeignKey("ChuongTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongTrinh");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.ChuongTrinh", b =>
                {
                    b.Navigation("DetailList");
                });

            modelBuilder.Entity("FestivalHue2020WebAPI.Models.LichDien", b =>
                {
                    b.Navigation("DetailList");
                });
#pragma warning restore 612, 618
        }
    }
}
